from __future__ import annotations

from pathlib import Path
from pkgutil import extend_path


__path__ = extend_path(__path__, __name__)  # type: ignore[name-defined]
ROOT = Path(__file__).resolve().parent.parent
SRC_PACKAGE = ROOT / "src" / "txflow"
if SRC_PACKAGE.exists():
    __path__.append(str(SRC_PACKAGE))  # type: ignore[attr-defined]

from .analysis import analyze_transactions, analyze_transactions_from_path
from .catalog import build_label_catalog, export_label_catalog_json, export_label_catalog_markdown
from .ledger_ops import (
    GraphDatasetSummary,
    LedgerReviewRow,
    MirrorAnnotationRow,
    MirrorReviewRow,
    NormalizedTransaction,
    OwnerReviewRow,
    OwnerSummaryReport,
    OwnerSummaryRow,
    RuleReviewBucket,
    RuleReviewSummary,
    RuleSummaryBucket,
    RuleSummaryReport,
    RuleAuditRow,
    build_mirror_annotations,
    build_mirror_review_rows,
    build_owner_review_roles,
    build_owner_review_rows,
    build_ledger_review_rows,
    build_rule_audit_rows,
    build_rule_review_summary,
    build_rule_summary,
    build_duplicate_transaction_ids,
    build_review_flags,
    export_graph_dataset_summary,
    export_ledger_review_csv,
    export_ledger_review_xlsx,
    export_mirror_annotations_csv,
    export_mirror_annotations_jsonl,
    export_mirror_review_csv,
    export_mirror_review_xlsx,
    export_normalized_ledgers,
    export_owner_review_csv,
    export_owner_review_xlsx,
    export_owner_summary_csv,
    export_owner_summary_json,
    export_rule_audit_csv,
    export_rule_audit_xlsx,
    export_rule_review_summary_json,
    export_rule_review_summary_markdown,
    export_rule_summary_json,
    export_rule_summary_markdown,
    load_mirror_annotations,
    load_normalized_ledgers,
    normalize_workbook,
    summarize_graph_dataset,
    summarize_owner_activity,
)
from .ingest import load_transactions, load_transactions_from_path
from .labels import LabelManifest, annotate_transaction_ids, build_label_index, load_label_manifest, load_label_manifests
from .model import BaselineTextClassifier, example_to_tokens, train_baseline_classifier
from .owners import OwnerAnnotation, OwnerLookup, load_owner_annotations
from .report_io import ensure_parent, write_json_file, write_markdown_lines
from .rule_config import RuleSignals, detect_rule_signals, derive_trade_pattern, flow_family_for_trade_pattern
from .roles import (
    RoleAnnotation,
    RoleLookup,
    export_role_annotations_csv,
    export_role_annotations_jsonl,
    load_role_annotations,
)
from .training import (
    DatasetSplit,
    build_positive_training_samples,
    build_training_examples,
    export_training_examples_csv,
    export_training_examples_jsonl,
    export_split_csv,
    export_split_jsonl,
    export_training_samples_csv,
    export_training_samples_jsonl,
    split_training_examples,
)
from .report import render_json_report, render_markdown_report
from .round_ops import (
    RoundBootstrap,
    RoundReport,
    bootstrap_round,
    build_round_report,
    export_round_bootstrap_json,
    export_round_bootstrap_markdown,
    export_round_report_json,
    export_round_report_markdown,
    load_review_stats,
)
from .thresholds import (
    OperatingThresholdRecommendation,
    ReviewWorkloadForecast,
    ReviewWorkloadRow,
    ThresholdSweepReport,
    ThresholdSweepRow,
    export_operating_threshold_json,
    export_operating_threshold_markdown,
    export_review_workload_json,
    export_review_workload_markdown,
    export_threshold_sweep_json,
    export_threshold_sweep_markdown,
    review_workload_forecast,
    score_threshold_sweep,
    select_operating_threshold,
)
from .triage import (
    RowTriage,
    WorkbookTriage,
    export_triage_json,
    export_triage_markdown,
    scan_workbook_directory,
    train_global_classifier,
    triage_workbook,
)
from .graph_risk import (
    GraphRiskModel,
    GraphRowScore,
    GraphTriageReport,
    GraphWorkbookSummary,
    export_graph_triage_json,
    export_graph_triage_markdown,
    score_directory,
)

__all__ = [
    "analyze_transactions",
    "analyze_transactions_from_path",
    "build_label_catalog",
    "export_label_catalog_json",
    "export_label_catalog_markdown",
    "NormalizedTransaction",
    "GraphDatasetSummary",
    "LedgerReviewRow",
    "RuleReviewBucket",
    "RuleReviewSummary",
    "RuleSummaryBucket",
    "RuleSummaryReport",
    "RuleAuditRow",
    "MirrorReviewRow",
    "MirrorAnnotationRow",
    "OwnerSummaryRow",
    "OwnerSummaryReport",
    "OwnerReviewRow",
    "build_duplicate_transaction_ids",
    "build_review_flags",
    "build_ledger_review_rows",
    "build_rule_audit_rows",
    "build_rule_review_summary",
    "build_rule_summary",
    "build_mirror_review_rows",
    "build_mirror_annotations",
    "normalize_workbook",
    "export_normalized_ledgers",
    "export_ledger_review_csv",
    "export_ledger_review_xlsx",
    "export_rule_audit_csv",
    "export_rule_audit_xlsx",
    "export_rule_review_summary_json",
    "export_rule_review_summary_markdown",
    "export_rule_summary_json",
    "export_rule_summary_markdown",
    "load_normalized_ledgers",
    "load_mirror_annotations",
    "summarize_graph_dataset",
    "export_graph_dataset_summary",
    "export_mirror_review_csv",
    "export_mirror_review_xlsx",
    "export_mirror_annotations_csv",
    "export_mirror_annotations_jsonl",
    "summarize_owner_activity",
    "build_owner_review_rows",
    "build_owner_review_roles",
    "export_owner_review_csv",
    "export_owner_review_xlsx",
    "export_owner_summary_csv",
    "export_owner_summary_json",
    "load_transactions",
    "load_transactions_from_path",
    "LabelManifest",
    "annotate_transaction_ids",
    "build_label_index",
    "load_label_manifest",
    "load_label_manifests",
    "BaselineTextClassifier",
    "example_to_tokens",
    "train_baseline_classifier",
    "OwnerAnnotation",
    "OwnerLookup",
    "load_owner_annotations",
    "RoleAnnotation",
    "RoleLookup",
    "load_role_annotations",
    "export_role_annotations_csv",
    "export_role_annotations_jsonl",
    "DatasetSplit",
    "build_positive_training_samples",
    "build_training_examples",
    "export_training_examples_csv",
    "export_training_examples_jsonl",
    "export_split_csv",
    "export_split_jsonl",
    "export_training_samples_csv",
    "export_training_samples_jsonl",
    "split_training_examples",
    "render_json_report",
    "render_markdown_report",
    "ensure_parent",
    "write_json_file",
    "write_markdown_lines",
    "RuleSignals",
    "detect_rule_signals",
    "derive_trade_pattern",
    "flow_family_for_trade_pattern",
    "RoundReport",
    "RoundBootstrap",
    "load_review_stats",
    "build_round_report",
    "export_round_report_json",
    "export_round_report_markdown",
    "bootstrap_round",
    "export_round_bootstrap_json",
    "export_round_bootstrap_markdown",
    "ThresholdSweepRow",
    "ThresholdSweepReport",
    "ReviewWorkloadRow",
    "ReviewWorkloadForecast",
    "OperatingThresholdRecommendation",
    "score_threshold_sweep",
    "export_threshold_sweep_json",
    "export_threshold_sweep_markdown",
    "review_workload_forecast",
    "export_review_workload_json",
    "export_review_workload_markdown",
    "select_operating_threshold",
    "export_operating_threshold_json",
    "export_operating_threshold_markdown",
    "RowTriage",
    "WorkbookTriage",
    "export_triage_json",
    "export_triage_markdown",
    "scan_workbook_directory",
    "train_global_classifier",
    "triage_workbook",
    "GraphRiskModel",
    "GraphRowScore",
    "GraphTriageReport",
    "GraphWorkbookSummary",
    "export_graph_triage_json",
    "export_graph_triage_markdown",
    "score_directory",
]
